language: java

install: true
jdk:  
 - oraclejdk8

sudo: false

os:
  - windows
branches:
  only:
  - master
notifications:
  email:
  - sharomov.v@gmail.com
      on_success: always
    on_failure: never
